name: Upgrade

on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
    - run: echo "::set-output name=job_1::pling"
    - run: echo "x${{ github.action_path }}y"
    - run: sleep 5
        
  job_2:
    runs-on: ubuntu-latest
    steps:
    - run: echo echo "::set-output name=job_2::plong"
    - run: echo "x${{ github.action_path }}y"
    - run: sleep 5

